name: wholesomeness_scanner
description: Scanner project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  nice_button: ^0.1.7
  simple_animations: ^2.2.1
  custom_radio_grouped_button: any
  pimp_my_button: any
  percent_indicator: ^2.1.5
  flutter_screenutil: ^2.3.0
  argon_buttons_flutter: ^1.0.6
  flutter_spinkit: ^4.1.2
  flutter_native_splash: ^0.1.9
  google_fonts: ^1.1.0
  ads: ^1.7.3
  firebase_admob: ^0.9.0
  firebase_core: ^0.5.0
  firebase_analytics: ^5.0.2
  connectivity: ^0.4.9+2
  animate_do: ^1.7.3
  confetti: ^0.5.4+1
  intl: ^0.16.1
  intl_translation: ^0.17.10+1
  esys_flutter_share: ^1.0.2
  path_provider: ^1.6.14
  url_launcher: ^5.5.3

flutter_native_splash:
  image: assets/splash.png
  color: "34495e"
  fill: true


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true
flutter_intl:
  enabled: true
